apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: eurekaserver
          image: igor2435/eurekaserver:latest
          ports:
            - containerPort: 8761
        - name: mss1
          image: igor2435/mss1:latest
          env:
            - name: PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: "mss1"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://localhost:8761/eureka/"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
    - name: eurekaserver-port
      port: 8761
      targetPort: 8761
    - name: mss1-port
      port: 8080
      targetPort: 8080
  selector:
    app: my-app
